# Generated by Django 3.0.8 on 2020-07-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pictures',
            new_name='picture',
        ),
    ]
