# Generated by Django 3.0.8 on 2020-07-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0004_auto_20200703_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
